In [66]:
%load_ext tensorboard
%tensorboard --logdir Testing_Results_problem_0/

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


Reusing TensorBoard on port 6008 (pid 24740), started 0:00:01 ago. (Use '!kill 24740' to kill it.)

In [3]:
# !pip install tensorflow
# !pip install -U tbparse

  Obtaining dependency information for tbparse from https://files.pythonhosted.org/packages/42/c4/08dd8ce00d6764c7df33088cb0e1a6947b4107241d47c64999beb079bfb5/tbparse-0.0.8-py3-none-any.whl.metadata


In [4]:
from tbparse import SummaryReader

log_dir = "Testing_Results_problem_0/"
reader = SummaryReader(log_dir)
df = reader.scalars
print(df)

c:\Users\arabp\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (



     step                                                tag         value
0     160  Difference in predictions between Predicted an...  2.174293e-13
1     161  Difference in predictions between Predicted an...  2.773176e-13
2     162  Difference in predictions between Predicted an...  4.092656e-13
3     163  Difference in predictions between Predicted an...  4.361979e-13
4     164  Difference in predictions between Predicted an...  5.244183e-13
..    ...                                                ...           ...
662   196                                          Loss Plot  8.614458e-03
663   196                                          Loss Plot  6.498047e+00
664   197                                          Loss Plot  6.817100e+00
665   197                                          Loss Plot  1.020096e-02
666   197                                          Loss Plot  6.816903e+00

[667 rows x 3 columns]


In [29]:
df.tail()

step        tag     value
662   196  Loss Plot  0.008614
663   196  Loss Plot  6.498047
664   197  Loss Plot  6.817100
665   197  Loss Plot  0.010201
666   197  Loss Plot  6.816903

In [38]:
import torch
import tensorflow as tf

In [32]:
A = torch.tensor(
    [
        [
            -0.4040,
            0.0186,
            -0.0486,
            -0.0660,
            0.0609,
            -0.0442,
            -0.0021,
            -0.0094,
            -0.0408,
            -0.0314,
        ],
        [
            0.0186,
            -0.4089,
            0.0276,
            0.0330,
            -0.0010,
            0.0086,
            0.0443,
            -0.0449,
            -0.0759,
            0.0058,
        ],
        [
            -0.0486,
            0.0276,
            -0.3523,
            -0.0743,
            -0.0015,
            -0.0479,
            0.0278,
            -0.0582,
            0.0223,
            0.0316,
        ],
        [
            -0.0660,
            0.0330,
            -0.0743,
            -0.3776,
            0.0590,
            -0.0303,
            0.0185,
            -0.0527,
            0.0237,
            -0.0110,
        ],
        [
            0.0609,
            -0.0010,
            -0.0015,
            0.0590,
            -0.4735,
            0.0831,
            0.0656,
            -0.0008,
            0.0161,
            0.0860,
        ],
        [
            -0.0442,
            0.0086,
            -0.0479,
            -0.0303,
            0.0831,
            -0.3675,
            0.0324,
            0.0482,
            -0.0132,
            0.0115,
        ],
        [
            -0.0021,
            0.0443,
            0.0278,
            0.0185,
            0.0656,
            0.0324,
            -0.3613,
            0.0014,
            -0.0362,
            0.0599,
        ],
        [
            -0.0094,
            -0.0449,
            -0.0582,
            -0.0527,
            -0.0008,
            0.0482,
            0.0014,
            -0.4143,
            -0.0356,
            -0.0334,
        ],
        [
            -0.0408,
            -0.0759,
            0.0223,
            0.0237,
            0.0161,
            -0.0132,
            -0.0362,
            -0.0356,
            -0.4326,
            -0.0260,
        ],
        [
            -0.0314,
            0.0058,
            0.0316,
            -0.0110,
            0.0860,
            0.0115,
            0.0599,
            -0.0334,
            -0.0260,
            -0.4057,
        ],
    ]
)

tensor([[-0.4040,  0.0186, -0.0486, -0.0660,  0.0609, -0.0442, -0.0021, -0.0094,
         -0.0408, -0.0314],
        [ 0.0186, -0.4089,  0.0276,  0.0330, -0.0010,  0.0086,  0.0443, -0.0449,
         -0.0759,  0.0058],
        [-0.0486,  0.0276, -0.3523, -0.0743, -0.0015, -0.0479,  0.0278, -0.0582,
          0.0223,  0.0316],
        [-0.0660,  0.0330, -0.0743, -0.3776,  0.0590, -0.0303,  0.0185, -0.0527,
          0.0237, -0.0110],
        [ 0.0609, -0.0010, -0.0015,  0.0590, -0.4735,  0.0831,  0.0656, -0.0008,
          0.0161,  0.0860],
        [-0.0442,  0.0086, -0.0479, -0.0303,  0.0831, -0.3675,  0.0324,  0.0482,
         -0.0132,  0.0115],
        [-0.0021,  0.0443,  0.0278,  0.0185,  0.0656,  0.0324, -0.3613,  0.0014,
         -0.0362,  0.0599],
        [-0.0094, -0.0449, -0.0582, -0.0527, -0.0008,  0.0482,  0.0014, -0.4143,
         -0.0356, -0.0334],
        [-0.0408, -0.0759,  0.0223,  0.0237,  0.0161, -0.0132, -0.0362, -0.0356,
         -0.4326, -0.0260],
        [-0.0314,  

In [35]:
A**(1/2)

tensor([[   nan, 0.1364,    nan,    nan, 0.2468,    nan,    nan,    nan,    nan,
            nan],
        [0.1364,    nan, 0.1661, 0.1817,    nan, 0.0927, 0.2105,    nan,    nan,
         0.0762],
        [   nan, 0.1661,    nan,    nan,    nan,    nan, 0.1667,    nan, 0.1493,
         0.1778],
        [   nan, 0.1817,    nan,    nan, 0.2429,    nan, 0.1360,    nan, 0.1539,
            nan],
        [0.2468,    nan,    nan, 0.2429,    nan, 0.2883, 0.2561,    nan, 0.1269,
         0.2933],
        [   nan, 0.0927,    nan,    nan, 0.2883,    nan, 0.1800, 0.2195,    nan,
         0.1072],
        [   nan, 0.2105, 0.1667, 0.1360, 0.2561, 0.1800,    nan, 0.0374,    nan,
         0.2447],
        [   nan,    nan,    nan,    nan,    nan, 0.2195, 0.0374,    nan,    nan,
            nan],
        [   nan,    nan, 0.1493, 0.1539, 0.1269,    nan,    nan,    nan,    nan,
            nan],
        [   nan, 0.0762, 0.1778,    nan, 0.2933, 0.1072, 0.2447,    nan,    nan,
            nan]])

In [36]:
A_eigen = torch.linalg.eig(A)

In [37]:
A_eigen

torch.return_types.linalg_eig(
eigenvalues=tensor([-0.6402+0.j, -0.2109+0.j, -0.2476+0.j, -0.2876+0.j, -0.3155+0.j, -0.5418+0.j,
        -0.5055+0.j, -0.3778+0.j, -0.4270+0.j, -0.4438+0.j]),
eigenvectors=tensor([[ 0.4421+0.j, -0.0250+0.j, -0.1368+0.j, -0.3029+0.j,  0.5583+0.j, -0.0244+0.j,
         -0.0983+0.j, -0.5546+0.j,  0.1484+0.j, -0.2045+0.j],
        [-0.0737+0.j,  0.2883+0.j,  0.1568+0.j, -0.0109+0.j,  0.4627+0.j,  0.5616+0.j,
         -0.1323+0.j,  0.4642+0.j,  0.3514+0.j, -0.0273+0.j],
        [ 0.2127+0.j,  0.0904+0.j,  0.6850+0.j, -0.2994+0.j, -0.2701+0.j, -0.2419+0.j,
         -0.4387+0.j,  0.0835+0.j,  0.1059+0.j, -0.2135+0.j],
        [ 0.3834+0.j,  0.1489+0.j, -0.0384+0.j,  0.7928+0.j,  0.1461+0.j, -0.2187+0.j,
         -0.3414+0.j,  0.0830+0.j, -0.0838+0.j, -0.0350+0.j],
        [-0.6241+0.j,  0.4156+0.j, -0.1424+0.j,  0.0853+0.j, -0.0566+0.j, -0.0657+0.j,
         -0.4260+0.j, -0.4291+0.j,  0.1740+0.j, -0.0827+0.j],
        [ 0.3089+0.j,  0.3339+0.j, -0.4691+0.j, -0.

In [44]:
C2_tf = tf.convert_to_tensor(torch.abs(A))
C2_sqrt = torch.from_numpy(tf.linalg.sqrtm(C2_tf).numpy())

In [45]:
C2_sqrt

tensor([[ 0.6293,  0.0119,  0.0359,  0.0491,  0.0425,  0.0317, -0.0034,  0.0026,
          0.0296,  0.0216],
        [ 0.0119,  0.6343,  0.0186,  0.0233, -0.0021,  0.0039,  0.0344,  0.0327,
          0.0569,  0.0014],
        [ 0.0359,  0.0186,  0.5855,  0.0583, -0.0058,  0.0369,  0.0209,  0.0433,
          0.0138,  0.0235],
        [ 0.0491,  0.0233,  0.0583,  0.6060,  0.0432,  0.0182,  0.0114,  0.0389,
          0.0145,  0.0032],
        [ 0.0425, -0.0021, -0.0058,  0.0432,  0.6779,  0.0626,  0.0478, -0.0035,
          0.0088,  0.0632],
        [ 0.0317,  0.0039,  0.0369,  0.0182,  0.0626,  0.5991,  0.0236,  0.0370,
          0.0073,  0.0031],
        [-0.0034,  0.0344,  0.0209,  0.0114,  0.0478,  0.0236,  0.5949, -0.0029,
          0.0261,  0.0456],
        [ 0.0026,  0.0327,  0.0433,  0.0389, -0.0035,  0.0370, -0.0029,  0.6381,
          0.0247,  0.0252],
        [ 0.0296,  0.0569,  0.0138,  0.0145,  0.0088,  0.0073,  0.0261,  0.0247,
          0.6530,  0.0175],
        [ 0.0216,  

In [58]:
L = [1, 2, 3, 4, 5]

In [52]:
import numpy as np

In [59]:
L = np.array(L)

In [64]:
np.abs(L).mean()

3.0