In [2]:
%load_ext tensorboard
%tensorboard --logdir Testing_Results_problem_0/

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


Reusing TensorBoard on port 6006 (pid 11080), started 0:00:06 ago. (Use '!kill 11080' to kill it.)

In [1]:
import torch

In [16]:
torch.log(torch.clamp(torch.tensor([0]), min=1e-20))

tensor([-46.0517])

In [24]:
torch.exp(torch.tensor(46))

tensor(9.4961e+19)

In [23]:
1e+20

1e+20

In [5]:
a = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

In [6]:
a**2

tensor([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])

In [7]:
torch.pow(a, 2)

tensor([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])